name: Artifacts in my workflow

on:
 push:
  branches:
   - anotherbranch

jobs:

 build:
  runs-on: ubuntu-latest
  steps:
   - name: "Checkout del repositorio"
     uses: actions/checkout@v3
     with:
      repository: jmoyano/cautious-meme
      ref: main
      path: ./buildmain
      
   - name: "Compilando main.c"
     run: gcc ./buildmain/main.c -o main
    
   - name: "Subiendo el artefacto" 
     uses: actions/upload-artifact@v3 
     with:
      name: envoutput
      path: ./buildmain
      
 test:
  needs: [ "build" ]
  runs-on: ubuntu-latest
  steps:
   - name: "Checkout del repositorio"
     uses: actions/checkout@v3
     
   - name: "Descargar el artefacto"
     uses: actions/download-artifact@v3
     with:
      name: envoutput
      path: ./main
    
   - name: "Ejecutando ls"
     run: ls
    
      
     