name: Artifacts in my workflow
on:
 push:
  branches:
   - anotherbranch

jobs:

 build:
  runs-on: ubuntu-latest
  steps:
   - name: "Checkout del repositorio"
     uses: actions/checkout@v3
     with:
      repository: jmoyano/cautious-meme
      ref: main
      
   - name: "Compilando main.c"
     run: gcc ./main.c -o main
    
   - name: "Subiendo el artefacto" 
     uses: actions/upload-artifact@v3 
     with:
      name: envoutput
      path: main
      
 test:
  needs: [ "build" ]
  runs-on: ubuntu-latest
  env:
   RESULTADO: 0
  steps:
   - name: "Checkout del repositorio"
     uses: actions/checkout@v3
     
   - name: "Descargar el artefacto"
     uses: actions/download-artifact@v3
     with:
      name: envoutput
    
   - name: "Ejecutando ls"
     run: ls
    
   - name: "Ejecutar main"
     run: |
      chmod +x ./main
      resultado=$(./main)
      if [ $resultado -eq 0 ]; then
       echo "::set-output name=resultado::Exito"
      else
       echo "::set-output name=resultado::Error"
      fi
          
     