name: Secrets in my workflow

on:
 push:
  branches:
   - anotherbranch

jobs:

 job1:
  runs-on: ubuntu-latest
  steps:
      
   - name: "Imprimiento un secret"
     run: echo ${{ secrets.SECRET_VARIABLE }}
      
     